package org.talend.daikon.serialize.jsonschema;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

import org.talend.daikon.properties.Properties;
import org.talend.daikon.properties.property.Property;

/**
 * Generate json-schema and ui-schema from {@ComponentProperties}, and only consider {@Property} and
 * {@Properties} inside.
 */
public class JsonBaseTool {

    /**
     * the className is generated by TypeUtils.toString(), this method is try to find the class by this string but may
     * failed
     * 
     * @param className
     * @return
     */
    protected static Class findClass(String className) {
        Class<?> aClass = null;
        try {
            aClass = Class.forName(className);
        } catch (ClassNotFoundException e) {
            int lastPosition = className.lastIndexOf(".");
            if (lastPosition < 0) {
                throw new RuntimeException(e);
            }
            className = className.substring(0, lastPosition) + "$" + className.substring(lastPosition + 1);
            return findClass(className);
        }
        return aClass;
    }

    protected static List<Property> getSubProperty(Properties cProperties) {
        List<Property> propertyList = new ArrayList<>();
        Field[] allFields = cProperties.getClass().getFields();
        for (Field field : allFields) {
            if (Property.class.isAssignableFrom(field.getType())) {
                try {
                    propertyList.add((Property) field.get(cProperties));
                } catch (IllegalAccessException e) {
                    throw new RuntimeException(e);
                }
            }
        }
        return propertyList;
    }

    protected static List<Properties> getSubProperties(Properties cProperties) {
        List<Properties> propertiesList = new ArrayList<>();
        Field[] allFields = cProperties.getClass().getDeclaredFields();
        for (Field field : allFields) {
            if (Properties.class.isAssignableFrom(field.getType())) {
                try {
                    propertiesList.add((Properties) field.get(cProperties));
                } catch (IllegalAccessException e) {
                    throw new RuntimeException(e);
                }
            }
        }
        return propertiesList;
    }
}
